### ISSUE TITLE
python script ending on button press

### ISSUE THREAD

**Issue by ghost** [smallest-cock/RL-Custom-Quickchat#1]
![image](https://github.com/smallest-cock/RL-Custom-Quickchat/assets/62274829/7efec9a7-a65c-4ba8-9c02-74a4871be5ec)

I have not changed anything from the example xbox script, and have pygame as well as pyautogui installed. using python 3.11.3

**Comment by smallest-cock** [comment]
I'm sorry to see this doesn't work properly.. It's because I don't own an Xbox controller to test on :(

I may buy one soon just to test on. I'm pretty sure this issue has something do with Xbox controller d-pad buttons being considered "hats" in pygame (as opposed to being considered regular "buttons" on PS4 controllers)

**Comment by smallest-cock** [comment]
> ![image](https://user-images.githubusercontent.com/62274829/253781757-7efec9a7-a65c-4ba8-9c02-74a4871be5ec.png)
> 
> I have not changed anything from the example xbox script, and have pygame as well as pyautogui installed. using python 3.11.3

I updated the code. It shouldn't crash on a button press anymore.
