### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hamzaelasmar** [smallest-cock/RL-Custom-Quickchat#4]
Sooo,
Currently Disable save modes laggs my game
I dont want it in the macro
which piece of code do i remove?

**Comment by hamzaelasmar** [comment]
that was fixed, but it doesn't work]
and make alphaconsole open

**Comment by smallest-cock** [comment]
@hamzaelasmar Do you mean you want to remove the macro which triggers `enableBallTexture()` completely, or do you just want to make the autoclicker skip the part where it clicks the "Disable Safe Mode" button?

If you want to remove the autoclicker functionality completely, you can just delete whatever macro contains `enableBallTexture()` in your main script (the whole `elif combine(...):` block)

If you want the autoclicker to skip the "Disable Safe Mode" button, would that mean you want to click the button yourself then have the autoclicker click the remaining buttons? I'm not sure I understand what you mean, sorry.

**Comment by smallest-cock** [comment]
I can also make a separate function (an alternative to `enableBallTexture()`) which clicks points on the screen based on a list of pre-saved coordinates... which should use less CPU resources (because there's no image searching going on), which may reduce lag. The only downside being: the pre-saved coordinates will become invalid if you move/resize the alphaconsole menu yourself.

Let me know if that sounds like what you need 👌

**Comment by hamzaelasmar** [comment]
I mean i want to click the button myself,
and if possible hopefully make the seperate function and teach non-coders how to change them,
if you want to i currently dont need it.
Thank you so much for responding.

**Comment by hamzaelasmar** [comment]
and for some reason i set up everything and the macro but it still doesn't change, and im sure i did all the steps

**Comment by smallest-cock** [comment]
@hamzaelasmar I updated the code to allow customization of the autoclicker. Check out the [autoclicker usage guide](https://github.com/smallest-cock/RL-Custom-Quickchat/blob/main/docs/Autoclicker.md) for info on how to use it

For your specific case I'd recommend trying this first:
```python
enableBallTexture(onlyUseCoordsForFastMode=True)
```
because it makes the autoclicker not use any image searching when clicking the "Disable Safe Mode" button, which should reduce CPU usage (and hopefully lag). Note: You would have to run the autoclicker once in freeplay or something (so it can find all the correct button coordinates), then all the runs after that would use those coordinates instead of image searching.

If the above function still causes lag, or you would rather manually click "Disable Safe Mode", you can copy [this example](https://github.com/smallest-cock/RL-Custom-Quickchat/blob/main/docs/Autoclicker.md#example) instead
